import About from '@/components/About'
import Hero from '@/components/Hero'
import Howitworks from '@/components/Howitworks'
import Preloader from '@/components/Preloader'
import Head from 'next/head'
import Services from './services'
import Featred from '@/components/Featured'
import Doctors from '@/components/Doctors'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Hero/>
     <Howitworks/>
     <About/>
     <Services/>
     <Featred/>
     <Doctors/>
    </>
  )
}
