name: Node.js CI

on:
  push:
    branches:
      - main # Change to your default branch if different

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    # Add more steps for your build, test, or deployment process if needed
